#!/usr/bin/env bash
#
# filepath :shell/02.xiubo.sh
# email: lebron1950@163.com
# author: lebron1950
# date: 2019/10/14
# modify_time: @times
# usage: location variable

a='hello world'
echo ${a}
b='23'
echo ${b}
c='4.445'
echo ${4.445}

